---
title: "CIND820 Markdown"
Author: Anastasios-Tom Kalantzis
output:
  word_document: default
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

## R Markdown
#Install and load the appropriate packages/libraries for the project.

```{r }

#install.packages("tidyverse")
#install.packages("ggplot2")
#install.packages("TSstudio")
#install.packages("dplyr")
#install.packages("corrplot")
#install.packages("janitor")
#install.packages("tidyr")
library(corrplot)
library(ggplot2)
library(tidyverse)
library(TSstudio)
library(dplyr)
library(tidyr)
library(janitor)

```

## Reading Data

```{r}
mls<-read.csv ("/Users/tomkalantzis/Desktop/CIND820 FINAL PROJECT/Final Project/MLS.csv",header=TRUE)
```


```{r}
head(mls)
str(mls)
sum(is.na(mls))
summary(mls)
```
# Standard deviation for all the numerical attributes 
```{r}
sd(mls$THouseYoYChange ,na.rm=TRUE)
sd(mls$CompYoYChange ,na.rm=TRUE)
sd(mls$SFDetachBenchmark , na.rm=TRUE)
sd(mls$SFdetachYoYChange , na.rm=TRUE)
sd(mls$SFAttachIndex , na.rm=TRUE)
sd(mls$SFAttachBenchmark, na.rm=TRUE)
sd(mls$THouseIndex, na.rm=TRUE)
sd(mls$THouseBenchmark, na.rm=TRUE)
sd(mls$ApartIndex, na.rm=TRUE)
sd(mls$ApartBenchmark, na.rm=TRUE)
sd(mls$ApartYoYChange, na.rm=TRUE)
sd(mls$ThouseYoYChange, na.rm=TRUE)
sd(mls$SFAttachYoYChange, na.rm=TRUE)

```
#Boxplots showing the outliers
```{r}
boxplot(mls$SFDetachIndex, na.rm=TRUE)
#boxplot(mls$CompyYoYChange, na.rm=TRUE)
boxplot(mls$SFDetachBenchmark, na.rm=TRUE)
boxplot(mls$CompIndex, na.rm=TRUE)
boxplot(mls$CompBenchmark, na.rm=TRUE)
#boxplot(mls$CompYoYChange, na.rm=TRUE)
#boxplot(mls$SFDetachYoYChange, na.rm=TRUE)
boxplot(mls$SFAttachIndex, na.rm=TRUE)
boxplot(mls$SFAttachBenchmark, na.rm=TRUE)
#boxplot(mls$SFAttachYoYChange, na.rm=TRUE)
boxplot(mls$THouseIndex, na.rm=TRUE)
boxplot(mls$THouseBenchmark, na.rm=TRUE)
#boxplot(mls$THouseYoYChange, na.rm=TRUE)
boxplot(mls$ApartIndex, na.rm=TRUE)
boxplot(mls$ApartBenchmark, na.rm=TRUE)
#boxplot(mls$ApartYoYChange, na.rm=TRUE)

```
#Histograms showing where the values are skewed 
```{r}
hist(mls$SFDetachBenchmark)
hist(mls$CompBenchmark)
hist(mls$SFAttachBenchmark)
hist(mls$THouseBenchmark)
hist(mls$ApartBenchmark)
```
#Corellation between attributes 
```{r}
cor(mls$SFDetachBenchmark, mls$SFAttachBenchmark, use="complete.obs")
cor(mls$SFDetachBenchmark, mls$THouseBenchmark, use="complete.obs")
cor(mls$SFDetachBenchmark, mls$ApartBenchmark,  use="complete.obs")

cor(mls$SFAttachBenchmark,mls$SFDetachBenchmark , use="complete.obs")
cor(mls$SFAttachBenchmark,mls$THouseBenchmark , use="complete.obs")
cor(mls$SFAttachBenchmark, mls$ApartBenchmark, use="complete.obs")

cor(mls$THouseBenchmark,mls$SFDetachBenchmark , use="complete.obs")
cor(mls$THouseBenchmark,mls$SFAttachBenchmark , use="complete.obs")
cor(mls$THouseBenchmark,mls$ApartBenchmark , use="complete.obs")

cor(mls$ApartBenchmark,mls$SFDetachBenchmark , use="complete.obs")
cor(mls$ApartBenchmark, mls$SFAttachBenchmark, use="complete.obs")
cor(mls$ApartBenchmark,mls$THouseBenchmark , use="complete.obs")

```
#EDA
```{r}

newmls<-c("SFAttachBenchmark","THouseBenchmark","ApartBenchmark","SFDetachBenchmark","Date")
mls1<-mls[newmls]
#mls1

mls2<-na.omit(mls1)
#mls2

normalize <- function(x){
  return ((x - min(x)) / (max(x) - min(x)))}

mls2$SFAttachBenchmark<-normalize(mls2$SFAttachBenchmark)
mls2$THouseBenchmark <- normalize(mls2$THouseBenchmark)
mls2$ApartBenchmark <- normalize(mls2$ApartBenchmark) 
mls2$SFDetachBenchmark <- normalize (mls2$SFDetachBenchmark)

Date1<- as.Date(mls2$Date)
#Date1

mls3<- cor(mls2[,c("SFAttachBenchmark","THouseBenchmark","ApartBenchmark","SFDetachBenchmark")])
corrplot(mls3, method="shade",type="upper")

ggplot(mls2, aes(x=Date1, y=THouseBenchmark  )) + 
        geom_point() +
        geom_smooth()
        
ggplot(mls2, aes(x=Date1, y=SFAttachBenchmark )) + 
        geom_point() +
        geom_smooth()
        
ggplot(mls2, aes(x=Date1, y=ApartBenchmark)) + 
        geom_point() +
        geom_smooth()
        
ggplot(mls2, aes(x=Date1, y=SFDetachBenchmark)) + 
        geom_point() +
        geom_smooth()
```